eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: eurekaClient
spring:
  application:
    name: api-gateway
zuul:
  routes:
    myroutes:
      path: /abc/**
      serviceId: user
      sensitiveHeaders:
# \u542F\u7528\u7AEF\u70B9 env

# \u66B4\u9732\u7AEF\u70B9 env \u914D\u7F6E\u591A\u4E2A,\u9694\u5F00
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env