eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: eurekaClient
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/w17731138318/config-repo
          password: 2wxSWING
          username: w17731138318
          basedir: /Users/wangweixin/IdeaProjects/cloud-demo/config-server/basedir